databases:
  - name: kinoushstore-db
    plan: free

services:
  - type: web
    name: kinoushstore
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn kinoushstore.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "kinoushstore.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://kinoushstore.onrender.com"
      - key: SITE_URL
        value: "https://kinoushstore.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: kinoushstore-db
          property: connectionString
